### ISSUE TITLE
useDynamicWidgets

### ISSUE THREAD

**Issue by pakerekchdz** [meilisearch/meilisearch-js-plugins#1223] opened 2023-08-10 19:39 UTC
Do you plan to deploy this to the meilisearch adapter.

I see that meilisearch has everything that is necessary.
https://www.meilisearch.com/docs/learn/fine_tuning_results/faceted_search

https://www.algolia.com/doc/api-reference/widgets/dynamic-facets/react/#hook-usage

**Comment by pakerekchdz** [comment] 2023-08-11 14:31
![image](https://github.com/meilisearch/meilisearch-js-plugins/assets/140351885/ba02907b-dab2-41cb-96af-f76130e26463)
Meilisearch instantsearch even sends a request - but this is not handled by mailisearch instantsearch.
`const { attributesToRender } = useDynamicWidgets({ facets: ['*'] })`
It shows an empty array all the time, and there should be available e.g.
`["color", "brand"] etc.`

**Comment by bidoubiwa** [comment] 2023-08-22 11:58
Hey @pakerekchdz, thanks for raising this. Closing as it is a duplicate of #1014

**Closed by bidoubiwa** 2023-08-22 11:58 UTC
